[project]
name = "electricity-prices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "osgridconverter>=0.1.3",
    "plotly>=6.8.0",
    "pvlive-api>=1.5.2",
    "requests>=2.34.2",
    "statsmodels>=0.14.6",
    "taipy>=4.1.1",
    "tqdm>=4.68.3",
]
